package edu.csustan.gradingsystem.test;

import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Date;

import org.junit.*;

import edu.csustan.gradingsystem.domain.Assignment;
import edu.csustan.gradingsystem.manager.AssignmentManager;

/**
 * 
 * @author Brandon Halpin
 * JUnit test for AssignmentManager class
 *
 */
public class AssignmentManagerTest{
	
	/**
	 * Methods tested:
	 * insertAssignment()
	 * getAssignmentByTitle()
	 * getAssignmentByID()
	 * deleteAssignmentByID()
	 * 
	 */
	@Test public void insertDeleteAssignmentTest(){
		System.out.println("insertDeleteAssignmentTest...");
		//Declare variables for new Assignment to be created
		Assignment assignment = new Assignment();
		AssignmentManager assignmentManager = new AssignmentManager();
		String title = "TestAssignment2";
		Date dueDate = Date.valueOf("2013-10-14");
		double totalPossibleScore = 20;
		int facultyID = 1;
		String courseID = "CS4800";
		int courseSec = 01;
		int studentID = 2;
		boolean available = true;
		String description = "This is a sample description.";
		String term = "Fall 2013";

		//Assign values to new Assignment
		assignment.setTitle(title);
		assignment.setDueDate(dueDate);
		assignment.setMaximumScore(totalPossibleScore);
		assignment.setFacultyID(facultyID);
		assignment.setCourseID(courseID);
		
		assignment.setIsAvailable(available);
		assignment.setAssignDesc(description);
		assignment.setCourseSec(courseSec);
		assignment.setTerm(term);

		//Insert new assignment into database
		assignmentManager.insertAssignment(assignment);
		//Retrieve new assignment by title(since ID is generated by database we don't know it yet)
		if(AllTests.DEBUG)System.out.println("Retrieving inserted object...");
		Assignment testAssignment = assignmentManager.getAssignmentByTitle(title);

		//Verify all data from the database matches the new object
		assertEquals(assignment.getTitle(), testAssignment.getTitle());
		assertEquals(assignment.getDueDate(), testAssignment.getDueDate());
		assertEquals(assignment.getMaximumScore(), testAssignment.getMaximumScore(), 0.0);
		assertEquals(assignment.getFacultyID(), testAssignment.getFacultyID());
		assertEquals(assignment.getCourseID(), testAssignment.getCourseID());
		//assertEquals(assignment.getStudentID(), testAssignment.getStudentID());



		if(AllTests.DEBUG)assignmentManager.printAllAssignments();
		
		//Remove new Test object from database
		if(AllTests.DEBUG)System.out.println("Deleting new object...");
		assignmentManager.deleteAssignmentByID(testAssignment.getAssignmentNo());
		if(AllTests.DEBUG)assignmentManager.printAllAssignments();

	}
}
